/**
 * All Perfomance indicators
 */
export enum ApiKeyFigure {
  IR_INTENSITY_ID = 1,
  SCE_ORIENTATION_ID = 2,
  SCA_ORIENTATION_ID = 3,
  SCA_FRICTION_ID = 4,
  MISSING_GLASS_TUBE_ID = 5,
  COATING_DEGRADATION_ID = 6,
  HIGH_HYDROGEN_CONCENTRATION_ID = 7,
  SCA_SDX_ID = 8,
  GLASS_TUBE_TEMPERATURE_ID = 9,
  HCE_RECOMMENDED_ACTION_CLASS_ID = 10,
  MISSING_MIRROR_ID = 11,
  OXYGEN_PENETRATION_ID = 12,
  SCE_SDX_ID = 13,
  SCA_ORTHO_IMAGES_RGB_ONLINE_ID = 14,
  SCA_ORTHO_IMAGES_IR_ID = 15,
  SCA_ORTHO_IMAGES_SDX_ID = 16,
  SCE_ALIGNMENT_ID = 17,
  SCA_TRACKING_DEVIATION_ID = 18,
  HCE_POSITION_ID = 19,
  SCA_ORTHO_IMAGES_RGB_OFFLINE_ID = 27,
  SCA_BALL_JOINT_FRICTION_ID = 28,
  HOT_GLASS_TUBE_ENDS_ID = 29,
}
