export enum ApiStates {
  UPLOADING = "UPLOADING",
  UPLOAD_FAILED = "UPLOAD_FAILED",
  PICK_ME_UP = "PICK_ME_UP",
  PROCESSING = "PROCESSING",
  PROCESS_FAILED = "PROCESS_FAILED",
  ABANDONED = "ABANDONED",
  FINISHED = "FINISHED",
}

export const ApiStateStruct = {
  UPLOADING: [ApiStates.PICK_ME_UP, ApiStates.UPLOAD_FAILED, ApiStates.ABANDONED],
  UPLOAD_FAILED: [ApiStates.UPLOADING, ApiStates.ABANDONED, ApiStates.PICK_ME_UP],
  PICK_ME_UP: [ApiStates.PROCESSING, ApiStates.ABANDONED],
  PROCESSING: [ApiStates.FINISHED, ApiStates.ABANDONED, ApiStates.PROCESS_FAILED],
  PROCESS_FAILED: [ApiStates.PROCESSING, ApiStates.ABANDONED],
  ABANDONED: [],
  FINISHED: [],
};
