export enum ApiStates {
  UPLOADING = "UPLOADING",
  UPLOAD_FAILED = "UPLOAD_FAILED",
  PICK_ME_UP = "PICK_ME_UP",
  PROCESSING = "PROCESSING",
  PROCESS_FAILED = "PROCESS_FAILED",
  ABANDONED = "ABANDONED",
  FINISHED = "FINISHED",
}
