export enum UploaderEvent {
  FILE_PROGRESS = "UPLOAD_FILE_PROGRESS",
  FILE_COMPLETE = "FILE_COMPLETE",
  FILE_CHUNK_COMPLETE = "FILE_CHUNK_COMPLETE",
  ERROR = "UPLOAD_ERROR",
  START_UPLOAD = "START_UPLOAD",
  UPLOAD_COMPLETE = "UPLOAD_COMPLETE",
  UPLOAD_CANCELED = "UPLOAD_CANCELED",
  RESUME_UPLOAD_AFTER_ERROR = "RESUME_UPLOAD_AFTER_ERROR",
}
